// --------------------------------------------------------------
// -                       Custom Scripts                       -
// --------------------------------------------------------------
//      All the custom scripts, remove the '//' to enable...     
//      Place your scripts here!


// ----------------------- Hi Class Juti Scripts ---------------------
npc: npc/hiclass/_functions.txt

npc: npc/hiclass/npc_Newbie_Freebie.txt
npc: npc/hiclass/npc_jobmaster.txt
npc: npc/hiclass/npc_lnwJuti.txt
npc: npc/hiclass/npc_warper.txt
npc: npc/hiclass/npc_buff.txt

npc: npc/hiclass/machine_cashcoin.txt